import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <label htmlFor="search">Search</label>
        <input id="search" name="search" type="search" />
        <div className="space-y-4">
          <div className="flex items-center gap-4">
            <Image
              width={200}
              height={200}
              src={"https://via.placeholder.com/400"}
              alt=""
            />
            <div>
              <h3>Title</h3>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
